In [10]:
import cv2

#this code uses 2 file 
# 1. haarcascade_frontalface_default.xml
# 2. pic.png

In [11]:
img=cv2.imread("pic.png",1)
print(type(img))
print(img.shape)
print(img)

<class 'numpy.ndarray'>
(400, 600, 3)
[[[160 161 158]
  [161 162 162]
  [164 165 163]
  ...
  [199 199 194]
  [201 198 196]
  [201 198 196]]

 [[163 164 160]
  [162 163 162]
  [162 163 161]
  ...
  [202 202 197]
  [199 199 194]
  [199 201 194]]

 [[163 164 159]
  [162 163 162]
  [162 163 161]
  ...
  [203 200 195]
  [200 202 197]
  [202 202 197]]

 ...

 [[189 189 189]
  [189 189 189]
  [189 189 189]
  ...
  [206 207 205]
  [206 207 205]
  [209 209 207]]

 [[189 189 189]
  [189 189 189]
  [189 189 189]
  ...
  [207 209 207]
  [206 207 205]
  [209 209 207]]

 [[186 186 186]
  [186 186 186]
  [189 189 189]
  ...
  [209 209 207]
  [207 207 205]
  [209 209 207]]]


In [ ]:
cv2.imshow("abc",img)
cv2.waitKey(0)

resize_img=cv2.resize(img, ( int(img.shape[1]/2),int(img.shape[0]/2) ) )
cv2.imshow("abc",resize_img)
cv2.waitKey(0)

In [ ]:
face_cascade=cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    
cv2.imshow("abc",gray_image)
cv2.waitKey(0)

faces=face_cascade.detectMultiScale(gray_image,scaleFactor=1.05,minNeighbors=5)

for x,y,w,h in faces:
    i+=1
    img=cv2.rectangle(img, (x,y), (x+w, y+h), (0,255,0), 3 )

    
cv2.imshow("abc",img)
cv2.waitKey(0)

cv2.destroyAllWindows()
    